### PR TITLE
replace superagent with axios

### LINKED ISSUE #124: Replace superagent with a different request library
There's been a lot of discussion surrounding this in the past. We need a library that works both client-side and server-side, supports being browserified, doesn't expose globals (`isomorphic-fetch`) and doesn't break the current API.

Currently our tests are failing due to a security vulnerability in superagent:

- https://nodesecurity.io/advisories/479
- https://github.com/visionmedia/superagent/issues/1259

I may be able to own this and get it handled in the next day or so, depending on how urgent we feel this vulnerability is.

Any suggestions for replacement libraries?

/cc @stevenmiller888 @nettofarah @vadimdemedes

### PR DESCRIPTION
**Pull request by stephenmathieson**
This patch removes our dependency on superagent and replaces it with
axios.

Axios:

- works in the browser
- can be browserified
- works in node
- doesn't leak globals
- has no (known) security vulnerabilities
- is better maintained than superagent

Closes #124.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -224,20 +210,33 @@ class Analytics {
...
+      method: 'POST',
+      url: `${this.host}/v1/batch`,
+      data
+    }
+
+    if (this.timeout) {
+      req.timeout = typeof this.timeout === 'string' ? ms(this.timeout) : this.timeout
+    }
+
+    axios(req)
```
Comment (vadimdemedes) [inline index.js]: This could be rewritten as:

```js
axios(req)
  .catch(err => {
    if (err.response) {
      err = new Error(err.response.statusText)
    }
    
    return err
  })
  .then(err => {
    callbacks.forEach(callback => callback(err))
    callback(err, data)
  })
```

File: index.js [hunk 2]
```diff
@@ -49,11 +33,13 @@ class Analytics {
     this.queue = []
     this.writeKey = writeKey
     this.host = removeSlash(options.host || 'https://api.segment.io')
-    this.retryCount = options.retryCount || 3
     this.timeout = options.timeout || false
     this.flushAt = Math.max(options.flushAt, 1) || 20
     this.flushInterval = options.flushInterval || 10000
     this.flushed = false
+
+    // setup retries
```
Comment (vadimdemedes) [inline index.js]: I think comment can be removed, since the code is pretty self-explanatory.

Comment (stephenmathieson) [reply index.js]: Good point. Will remove.

File: index.js (hunk 1 above)
Comment (stephenmathieson) [reply index.js]: Not quite. The furfilled callback receives the "response" from axios (see https://github.com/axios/axios#response-schema). To get this to work, we could do something like:

```
.catch(err => {
  if (err.response) {
    err = new Error(err.response.statusText)
  }
  return err
}).then(err => {
  if (!(err instanceof Error)) {
    err = undefined
  }
  
  callbacks.forEach(callback => callback(err))
  callback(err, data)

  debug('flushed: %o', data)
})
```

But that feels pretty awkward to me.

Comment (stephenmathieson) [reply index.js]: Hmm, could also do:

```js
axios(req)
.then(res => {}) // ignore the response
.catch(err => {
  if (err.response) {
    err = new Error(err.response.statusText)
  }
  return err
})
.then(err => {
  callbacks.forEach(callback => callback(err))
  callback(err, data)

  debug('flushed: %o', data)
})
```

but this also feels a bit strange.

Comment (vadimdemedes) [reply index.js]: You are right, let's leave it like it is in the PR, with a few minor adjustments (will comment separately).

File: index.js [hunk 3]
```diff
@@ -224,20 +209,33 @@ class Analytics {
...
+
+    if (this.timeout) {
+      req.timeout = typeof this.timeout === 'string' ? ms(this.timeout) : this.timeout
+    }
+
+    axios(req)
+    .then(() => done())
+    .catch(err => {
+      if (err.response) {
+        const error = new Error(err.response.statusText)
```
Comment (vadimdemedes) [inline index.js]: => `err = new Error(err.response.statusText)`

Comment (stephenmathieson) [reply index.js]: Maybe it’s just that I’ve been writing a lot of Golang lately (and `govet` yells), but I think shadowing the existing variable decreases readability. I’m open to changing this if you have a strong opinion here tho

Comment (vadimdemedes) [reply index.js]: I hate overwriting variables either, const all the way. Just thought that in this block it wouldn't matter. It can stay that way too, not a big deal.
